#!/usr/bin/env python
import rospy
import numpy as np
from geometry_msgs.msg import PoseWithCovarianceStamped


def convert(data):
    pub = rospy.Publisher('/dvl/converted/pose', PoseWithCovarianceStamped, queue_size=10)
    msg = PoseWithCovarianceStamped()
    msg = data
    msg.header.frame_id = "world"

    pub.publish(msg)


def listener():
    rospy.init_node('dvl_converter')
    rospy.Subscriber('/dvl/pose', PoseWithCovarianceStamped, convert)
    rospy.spin()


if __name__ == '__main__':
    listener()
